server:
  port: 8083
kafka:
  bootstrap-servers: 192.168.2.10:9092
  security-protocol: PLAINTEXT
  topic: orderStatus
  groupId: deliveries
spring:
  zipkin:
    service:
      name: delivery
    baseUrl: http://192.168.1.42:9411/
  application:
    name: delivery
  sleuth:
    sampler:
      probability: 1.0
    web:
      skip-pattern: (^cleanup.*)
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true